# Site
repository: sxiii/sxiii.github.io
# favicon: images/favicon.ico

# Personal info
name: Den Ivanov
title: IT-Manager & Bachelor of Business Administration
email: sxiii@pm.me
website: sxiii.ru

# Social links
twitter_username: sxiii
github_username:  sxiii
facebook_username: sxiii
# dribbble_username: jekyll
# flickr_username: jekyll
instagram_username: securityxiii
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Den and I'm an IT-Manager.

  I am most skilled in: <mark>Linux</mark>, <mark>Bash</mark>, <mark>HTML/CSS</mark>, <mark>PHP</mark>, <mark>Python</mark>, and <mark>Eating Pizza</mark>

  Also I'm a cryptoblogger, opensource software and electric vehicles expert.
  
# Projects Section
projects_title: My projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in hardware and software engineering some of my other interests and hobbies are:
   - Photography
   - Travelling
   - [Blogging](https://steemit.com/@sxiii)
   - Gaming


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
