# Site
repository: sxiii/sxiii.github.io
# favicon: images/favicon.ico

# Personal info
name: Den Ivanov
title: IT-Manager & Bachelor of Business Administration
email: sxiii@pm.me
website: sxiii.ru

# Social links
twitter_username: sxiii
github_username:  sxiii
facebook_username: sxiii
# dribbble_username: jekyll
# flickr_username: jekyll
instagram_username: securityxiii
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Den and I'm an IT-Manager.

  I am most skilled in: <mark>Linux</mark>, <mark>Bash</mark>, <mark>HTML/CSS</mark>, <mark>PHP</mark>, <mark>Python</mark>, and <mark>Eating Pizza</mark>
  
  If you want a short summary, I'm a cryptoblogger, photographer, opensource software developer and electric vehicles expert.
  
  For the long story, keep on reading:
   
  I am an open-minded, ready to learn and to do person, always looking at alternative 
  solutions that helps to create innovative, eco-friendly and people-ish things. 
  And I believe that knowledge belongs to each of us and to all of us, to whole humanity!

  In my work, I am hardware and software engineer. I developed several hardware solutions, 
  including drones, 3D printers, home automation, business automation (sun collector system, 
  automatic sprinklers, etc.), developing microelectronics, electric vehicles and more. 
  
  I own small office and tight developers group in Rostov-on-Don. We are in charge of IT society 
  of Rostov region. I am also working as an eco-activist, freedom thinker, open minded person.

  I have experience in working with opensource/linux solutions: distros, databases, web servers, 
  built-in solutions etc. 
  
  Also I am working with Electric Cars, alternative energy solutions, electronics and electrics 
  towards the global movement for the greater, greener tomorrow.

  Last but not least, I work with crypto-scene. We held several cryptocurrency/blockchain 
  hackathons in Rostov-on-Don, meetups and other events. I am fan of BitShares and EOS cryptocurrencies, 
  and I'm having several blogs: Steemit (mostly english), Golos (mostly Russian), and others. 
  I write about linux, opensource, hardware, trips across the globe, cryptocurrency, devices, 
  new distributions and little on psychology and politics. 

  In the modern time I am becoming skillful techno-urbanist and I love to build comfortable and 
  techy space for human being. Planning to create a well-projected city/community in the nearest future.

# Projects Section
projects_title: My projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  When I have free time, I do coding and blogging. Here are some of my blogs:
   - [Steemit](https://steemit.com/@sxiii)
   - [Golos](https://golos.io/@sxiii)
   - [VOX](https://vox.community/@sxiii)
   - [Whaleshares](https://whaleshares.io/@sxiii)
   - [Serey](https://serey.io/@sxiii)
   - [Scorum](https://scorum.com/en-us/profile/@sxiii)
   - [Weku](https://deals.weku.io/@sxiii)
   - [VIZ](https://viz.world/@sxiii)
   - [Smoke](https://smoke.network/@sxiii)
   - [Bearshares](https://bearshares.com/@sxiii)
   - [WeYouMe](https://alpha.weyoume.io/@sxiii)
   - [Gaming](https://steamcommunity.com/id/sxiii/)

   Also, I am huge fan of traveling and photography, heavy melodic music so you can meet me at nearly any place of the world.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
